config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'top/main'
  resources :cartitems, only: [:new, :create, :destroy]
  resources :carts, only: [:show]

  root 'top#main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
    private
        def current_cart
            if session[:cart_id]
                cart = Cart.find(session[:cart_id])
            else
                cart = Cart.create
                session[:cart_id] = cart.id
            end
            cart
        end
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  def new
    @cart_item = CartItem.new
  end
  
  def create
    c = CartItem.new(product_id: params[:cart_item][:product_id], cart_id: current_cart.id, qty: params[:cart_item][:qty])
    c.save
    redirect_to root_path
  end
  
  def destroy
    CartItem.find(params[:id]).destroy
    redirect_to cart_path(current_cart.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cartitems = CartItem.where(cart_id: current_cart.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    p = Product.new(name: params[:product][:name], price: params[:product][:price])
    p.save
    redirect_to root_path
  end
  
  def destroy
    Product.find(params[:id]).destroy
    redirect_to root_path
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
       redirect_to products_path 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cartitems/new.html.erb
<%= form_with model: @cart_item,url:cartitems_path do |f| %>
  <p>
    <%= f.label :name, '商品名' %>
    <%= Product.find(params[:product_id]).name %>
  </p>
  <p>
    <%= f.label :price, '価格' %>
    <%= Product.find(params[:product_id]).price %>
  </p>
  <p>
    <%= f.label :qty, '数量' %>
    <%= f.text_field :qty %>
  </p>
  <%= f.hidden_field :product_id, value: params[:product_id] %>
  <%= f.submit '商品を登録する' %>
<% end %>

app/views/carts/show.html.erb
<% @cartitems.each do |e| %>
  商品名：<%= Product.find(e.product_id).name %>
  価格：<%=  Product.find(e.product_id).price %>
　数量：<%=  e.qty %>
　<%= link_to '削除', cartitem_path(e), data: { turbo_method: :delete } %>
　<br>
<% end %>
  
<%= link_to "商品一覧に戻る", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @products.each do |e| %>
  商品名: <%= e.name %>, 価格: <%= e.price %>
  <%= link_to '削除', product_path(e), data: { turbo_method: :delete } %>
  <%= link_to 'カート追加', new_cartitem_path(product_id: e.id) %>
  <br>
<% end %>

<%= link_to "新規追加", new_product_path %>

<%= link_to "カートを見る", cart_path(current_cart.id) %>

app/views/products/new.html.erb
<%= form_with model: @product do |f| %>
  <p>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %>
  </p>
  <%= f.submit '登録' %>
<% end %>